### ISSUE TITLE
Get rid of if(!this)

### ISSUE THREAD

**Issue by whitequark** [whitequark/solvespace#70]
Apparently GCC 6 has finally started to take advantage of undefinedness of `NULL->x()`. See https://github.com/whitequark/solvespace/pull/69#issuecomment-193303628.

**Comment by whitequark** [comment]
Fixed in ac523c5106d.

**Comment by whitequark** [comment]
Not fixed. There's a null pointer dereference. To reproduce:
  * Extrude a circle
  * Force it to mesh

```
0x00000000004c42ea in SolveSpace::SBsp3::Insert (this=0x0, tr=0x39ebfb0, instead=0x7fffffffc850) at /home/whitequark/Work/solvespace/src/bsp.cpp:292
292         double dt[3] = { (tr->a).Dot(n), (tr->b).Dot(n), (tr->c).Dot(n) };
(gdb) bt
#0  0x00000000004c42ea in SolveSpace::SBsp3::Insert (this=0x0, tr=0x39ebfb0, instead=0x7fffffffc850) at /home/whitequark/Work/solvespace/src/bsp.cpp:292
#1  0x0000000000530d10 in SolveSpace::SMesh::AddAgainstBsp (this=0x7fffffffc850, srcm=0x7fffffffc898, bsp3=0x0)
    at /home/whitequark/Work/solvespace/src/mesh.cpp:250
#2  0x0000000000530fb2 in SolveSpace::SMesh::MakeFromUnionOf (this=0x7fffffffc850, a=0x7fffffffc8b0, b=0x7fffffffc898)
    at /home/whitequark/Work/solvespace/src/mesh.cpp:271
#3  0x000000000052dba3 in SolveSpace::Group::GenerateForBoolean<SolveSpace::SMesh> (this=0x34899d0, prevs=0x7fffffffc8b0, thiss=0x7fffffffc898, 
    outs=0x7fffffffc850, how=0) at /home/whitequark/Work/solvespace/src/groupmesh.cpp:172
#4  0x000000000052bc07 in SolveSpace::Group::GenerateShellAndMesh (this=0x34899d0) at /home/whitequark/Work/solvespace/src/groupmesh.cpp:345
#5  0x0000000000514ff5 in SolveSpace::SolveSpaceUI::GenerateAll (this=0xb43bc0 <SolveSpace::SS>, type=SolveSpace::SolveSpaceUI::GENERATE_DIRTY, 
    andFindFree=false, genForBBox=false) at /home/whitequark/Work/solvespace/src/generate.cpp:311
#6  0x0000000000556f12 in SolveSpace::TextWindow::ScreenChangeGroupOption (link=102, v=0) at /home/whitequark/Work/solvespace/src/textscreens.cpp:210
#7  0x000000000055efd5 in SolveSpace::TextWindow::MouseEvent (this=0xb43bc0 <SolveSpace::SS>, leftClick=true, leftDown=false, x=189, y=287)
    at /home/whitequark/Work/solvespace/src/textwin.cpp:1001
#8  0x00000000004bde13 in SolveSpace::TextWidget::on_button_press_event (this=0x2b0d0e0, event=0x3235c70)
    at /home/whitequark/Work/solvespace/src/gtk/gtkmain.cpp:1299
```

**Comment by whitequark** [comment]
Fixed.
